services:
  backend:
    build:
      context: ./Backend
    container_name: django_backend
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app
    env_file:
      - ./Backend/hanashop_api/config/.env
    depends_on:
      - db

  frontend:
    build:
      context: ./Frontend
    container_name: react_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - ./Backend/hanashop_api/config/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
