# Generated by Django 5.1.5 on 2025-03-06 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_api_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InventoryMovement',
            new_name='Inventory_movement',
        ),
    ]
