# Generated by Django 5.1.5 on 2025-03-06 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_api_app', '0004_alter_category_status_alter_info_customer_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory_movement',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
