# Generated by Django 5.1.5 on 2025-03-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_api_app', '0005_inventory_movement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_customer',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
