# Generated by Django 5.1.5 on 2025-03-06 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_api_app', '0006_alter_info_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_detail',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
