# Generated by Django 5.1.5 on 2025-03-06 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_api_app', '0008_rename_info_customer_infocustomer_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderdetail',
            unique_together={('order', 'product')},
        ),
    ]
