# Generated by Django 5.1.5 on 2025-03-06 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_api_app', '0009_alter_orderdetail_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infocustomer',
            name='email',
        ),
    ]
