# Generated by Django 5.1.5 on 2025-05-04 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_api_app', '0012_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='_skip_signal',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
