# Generated by Django 5.1.5 on 2025-05-04 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_api_app', '0013_product__skip_signal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='_skip_signal',
        ),
    ]
