name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend:
    runs-on: ubuntu-latest
    name: Frontend Build, Test and Lint
    needs: backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd Frontend
          npm install

      - name: Run ESLint
        run: |
          cd Frontend
          npx eslint src


      - name: Run Vitest Tests
        run: |
          cd Frontend
          npm run test -- --run

  backend:
    runs-on: ubuntu-latest
    name: Backend Build, Test and Lint

    services:
      postgres:
        image: postgres:alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd Backend
          pip install -r requirements.txt

      - name: Set environment variables
        run: |
          echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> Backend/hanashop_api/config/.env
          echo "DJANGO_DEBUG=${{ secrets.DJANGO_DEBUG }}" >> Backend/hanashop_api/config/.env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> Backend/hanashop_api/config/.env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> Backend/hanashop_api/config/.env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> Backend/hanashop_api/config/.env
          echo "POSTGRES_HOST=localhost" >> Backend/hanashop_api/config/.env
          echo "POSTGRES_PORT=5432" >> Backend/hanashop_api/config/.env
          echo "DATABASE_URL=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB" >> Backend/hanashop_api/config/.env

      - name: Run Pylint
        run: |
          cd Backend/hanashop_api
          export DJANGO_SETTINGS_MODULE=hanashop_api.settings
          pylint sales_api_app

      - name: Run Pytest
        run: |
          cd Backend/hanashop_api
          pytest

